FROM ahoereth/tf-base

# Intel optimized python 3
RUN wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB \
 && apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB \
 && wget https://apt.repos.intel.com/setup/intelproducts.list -O /etc/apt/sources.list.d/intelproducts.list \
 && apt-get update \
 && apt-get install -y --no-install-recommends intelpython3

# RUN rm /usr/bin/python3 \
#  && ln -s /opt/intel/intelpython3/bin/python3 /usr/bin/python3 \
#  && rm /usr/bin/python \
#  && ln -s /opt/intel/intelpython3/bin/python3 /usr/bin/python
# ENV CI_BUILD_PYTHON /opt/intel/intelpython3/bin/python3
# ENV PYTHON_BIN_PATH /opt/intel/intelpython3/bin/python3

# Intel optimized docker
# https://software.intel.com/en-us/articles/tensorflow-optimizations-on-modern-intel-architecture
RUN cd /tensorflow \
 && tensorflow/tools/ci_build/builds/configured CPU \
    bazel build \
        --config=mkl --copt="-DEIGEN_USE_VML" -c opt \
        tensorflow/tools/pip_package:build_pip_package && \
    bazel-bin/tensorflow/tools/pip_package/build_pip_package.sh /tmp/pip3 && \
    pip3 --no-cache-dir install --upgrade /tmp/pip3/tensorflow-*.whl && \
    rm -rf /tmp/pip3 && \
    rm -rf /root/.cache

WORKDIR /root
